services:
  ragwebapi:
    image: ${DOCKER_REGISTRY-}ragwebapi
    container_name: ragwebapi
    build:
      context: .
      dockerfile: RAGWebAPI/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_API_URL=http://host.docker.internal:11434
      - OLLAMA_EMBED_MODEL=mxbai-embed-large
      - OLLAMA_GENERATIVE_MODEL=llama3.1:8b
    networks:
     - rag_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
     
    #llama3.1:8b
    #http://rag.ollama:11434

  rag.database:
    build:
      context: ./postgres-vector
    container_name: rag.database
    environment:
      POSTGRES_USER: rag
      POSTGRES_PASSWORD: rag123
      POSTGRES_DB: rag
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./.containers/rag-database:/var/lib/postgreql/data
      - ./postgres-vector/init-vector.sql:/docker-entrypoint-initdb.d/init-vector.sql
    ports:
      - "5432:5432"
    networks:
     - rag_network

  
  # rag.ollama:
  #   build:
  #     context: ./ollama
  #   container_name: rag.ollama
  #   privileged: true
  #   ports:
  #     - "11434:11434"
  #   devices:
  #     - /dev/kfd
  #     - /dev/dri
  #   volumes:
  #     - ollama:/root/.ollama
  #   networks:
  #     - rag_network

  # ollama.generative:
  #   image: ollama/ollama:rocm
  #   privileged: true
  #   ports:
  #     - "11435:11434"
  #   devices:
  #     - /dev/kfd
  #     - /dev/dri
  #   volumes:
  #     - ollama2:/root/.ollama

networks:
  rag_network:

volumes:
  ollama: